version: '3.1'
services:
  dev-db:
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: acc123
      POSTGRES_DB: nest
    networks:
      - freecodecamp
  test-db:
    image: postgres:12
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: acc123
      POSTGRES_DB: notespace_test
    networks:
      - freecodecamp
 