version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: acc123
      POSTGRES_DB: notespace_dev
    networks:
      - freecodecamp # this is the network that the app will use to connect to the database
  test-db:
    image: postgres:13
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: acc123
      POSTGRES_DB: notespace_test
    networks:
      - freecodecamp
networks:
  freecodecamp: